-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE TABLE IF NOT EXISTS public.budgets
(
    id uuid NOT NULL,
    month integer,
    year integer,
    CONSTRAINT budgets_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.budgets
    OWNER to postgres;

ALTER TABLE IF EXISTS public.budgets
    ENABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE public.budgets TO anon;

GRANT ALL ON TABLE public.budgets TO authenticated;

GRANT ALL ON TABLE public.budgets TO postgres;

GRANT ALL ON TABLE public.budgets TO service_role;
