name: Deploy Migrations to Production

on:
    push:
        paths:
            - 'server/**'
        branches: [main]

defaults:
    run:
        working-directory: server

jobs:
    deploy:
        runs-on: ubuntu-22.04

        env:
            SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
            SUPABASE_DB_PASSWORD: ${{ secrets.PRODUCTION_DB_PASSWORD }}
            PRODUCTION_PROJECT_ID: pbpntcryhbrzxfizyasv

        steps:
            - uses: actions/checkout@v3

            - uses: supabase/setup-cli@v1
              with:
                  version: 1.0.0

            - run: |
                  supabase link --project-ref $PRODUCTION_PROJECT_ID
                  supabase db push
